Rama fork
AdrianVS99/symfonyLoteriaOnce pull request #2
Opened 2024-01-16 13:26 UTC by jorgetamaral

rama forked

2024-01-16 13:27 UTC, jorgetamaral commented
He enviado mi pull request

2024-01-17 07:28 UTC, AdrianVS99 requested changes
Debes hacer cambios

2024-01-17 07:29 UTC, AdrianVS99 reviewed
esta bastante bien

2024-01-17 07:29 UTC, AdrianVS99 approved these changes

2024-03-04 13:44 UTC, closed without merging